os:
  - linux
  - osx
  - windows

language: node_js

node_js:
  - 8
  - 10
  - lts/*
  - node

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
    - wine

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install wine-stable; fi

install:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then npm i -g npm; fi
  - npm install

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi

script:
  - npm run compile
  - npm run test
