os:
  - linux
  - osx

sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
    - wine

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wine-stable; fi

install:
  - npm i -g npm
  - npm install

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi

script:
  - npm run compile
  - npm run test
